### ISSUE TITLE
Peer review 3. Use of Milestones and Features in Issue Tracker

### ISSUE THREAD

**Issue by beichenc** [worldyn/crawler#34]
In general, good use of issues and some use of milestones (I know, milestones is not the most necessary tool anyway..). 

You can use labels to group your issues so you can more easily see if they are a feature, a bug, enhancement, etc.

A lot of issues don't have a description. Would be good to see some extra information apart from the title.

**Comment by osobo** [comment]
We have now started using labels for issues.
